# Generated by Django 5.1.1 on 2024-09-13 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_sugar_morning', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_sugar_after_breakfast', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_sugar_before_lunch', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_sugar_after_lunch', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_sugar_before_dinner', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_sugar_after_dinner', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_sugar_before_bedtime', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('medication_taken', models.BooleanField(default=False)),
                ('diet_details', models.TextField(blank=True, null=True)),
                ('foot_check_completed', models.BooleanField(default=False)),
                ('exercise_minutes', models.IntegerField(blank=True, null=True)),
                ('date_recorded', models.DateField()),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Checkups',
                'ordering': ['-date_updated'],
            },
        ),
    ]
