# Generated by Django 5.1.1 on 2024-09-26 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGlucose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(choices=[('Fasting', 'Fasting'), ('Postprandial', 'Postprandial'), ('Bedtime', 'Bedtime')], max_length=20)),
                ('glucose_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_of_reading', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.PositiveIntegerField()),
                ('diastolic', models.PositiveIntegerField()),
                ('time_of_reading', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DietaryIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks')], max_length=20)),
                ('carb_intake', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugary_foods', models.TextField(blank=True, null=True)),
                ('time_of_meal', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FootHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot_check_completed', models.BooleanField(default=False)),
                ('abnormalities', models.TextField(blank=True, null=True)),
                ('pain_level', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hydration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_intake', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dehydration_symptoms', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsulinUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insulin_type', models.CharField(choices=[('Long-acting', 'Long-acting'), ('Rapid-acting', 'Rapid-acting')], max_length=20)),
                ('dose_units', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_of_administration', models.TimeField()),
                ('injection_site', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Metformin', 'Metformin'), ('Insulin', 'Insulin')], max_length=100)),
                ('dose', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_taken', models.TimeField()),
                ('missed_dose', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodAndEmotionalWellBeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_rating', models.PositiveIntegerField()),
                ('notable_events', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('Walking', 'Walking'), ('Running', 'Running'), ('Cycling', 'Cycling'), ('Strength Training', 'Strength Training')], max_length=50)),
                ('duration', models.PositiveIntegerField()),
                ('intensity', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20)),
                ('time_of_exercise', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SleepPatterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sleep_quality', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=10)),
                ('wake_up_time', models.TimeField()),
                ('bedtime', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StepCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_steps', models.PositiveIntegerField()),
                ('daily_goal', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedToDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_logs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
