# Generated by Django 5.1.1 on 2024-09-25 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('patient', '0004_foothealthcheck_date_hydration_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedToDoctor',
            fields=[
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='assigned_logs', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
